.github/workflows/wallet_build.yml
.github/workflows/wallet_ci.yml
Cargo.lock
Cargo.toml
src/lib/store.rs
src/main.rs

- Fix test steps to be integrated with proper matrix run
- Fix CI to disable Carriage Returns on Windows
- Fix action by removing toolchain override
- Fix wrong hardcoded path failing on Windows
- Rename CI files, added Windows tests on standard CI
- Fix CI naming to reflect OS where it's running
- Fix to eliminate carriage returns on windows git pulls
- Fix CI to include Mac Intel builds, switched M1 to checks
- Fix CI to remove --release flag from builds
- Fix CI to exclude tests from wallet builds (now all moved to test CI)
Fixes #15

Improvements to CI and binaries build

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/lib/prompt.rs
src/lib/wallet.rs
src/main.rs

This PR adds the `withdraw` stake reward command to the CLI and removes the local rusk precondition for staking, thus completing the new stake spec.
Resolves #26

Withdraw stake

---

CHANGELOG.md
src/lib/mod.rs
src/lib/prompt.rs

Addresses inputed by users in interactive mode are now required to be 88 bytes long as per the base58 spec.
Resolves #28

Enhance address validity checks on interactive mode

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/lib/block.rs
src/lib/cache.rs
src/lib/clients.rs
src/lib/error.rs
src/lib/gql.rs
src/lib/mod.rs
src/main.rs

- Upgrade cache implementation to use `microkelvin` instead of
`rusqlite`
- Add `Block` trait for easier blocking on futures
- Use streaming `GetNotes` call instead of `GetNotesOwnedBy`
Resolves #32

Upgrade cache to use `microkelvin` persistance

---

CHANGELOG.md
Cargo.lock
Cargo.toml

- Block trait for easier blocking on futures [#32]
- Withdraw reward command [#26]
- Upgraded cache implementation to use `microkelvin` instead of `rusqlite` [#32]
- Use streaming `GetNotes` call instead of `GetNotesOwnedBy` [#32]
- Enhance address validity checks on interactive mode [#28]
- Prevent exit on prepare command errors [#27]
- Adapt balance to the new State [#24]
- Rename `withdraw-stake` to `unstake` [#26]
- Introduce Dusk type for currency management [#4]
- Fix cache bug preventing adding all notes to it [#35]
- Fix address validation by parsing address first [#35]

Release 0.8

---

src/lib/cache.rs

This prevents the bug described in #39 by deleting the old cache file on startup.

cache: remove old cache.db if found

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/lib/clients.rs
src/lib/prompt.rs
src/lib/wallet.rs
src/main.rs

This is a necessary first step to practically solve #11 
Besides structural changes, this PR introduces these user-facing changes: 
- New `--spendable` flag to `Balance` command
- New `--reward` flag to `StakeInfo` command
- No more dynamic status updates in headless mode (for now)
Resolves #40

Decouple command outputs between interactive and headless modes

---

src/lib/clients.rs
src/lib/config.rs
src/lib/error.rs
src/lib/mod.rs
src/lib/rusk.rs
src/main.rs

While resolving #43, I took the chance to do a bit of refactoring, resulting in `Rusk` structure moving to its own `RuskClient` type outside the `main.rs`. It feels appropriate to have it somewhere else now that it's become a little bigger, as the `Interceptor` in charge of introducing the headers creates some noise in the code.
Resolves #43
See also https://github.com/dusk-network/rusk/pull/718

Add rusk version headers to all gRPC requests

---

CHANGELOG.md
Cargo.toml
README.md
config.toml
src/bin/command.rs
src/bin/error.rs
src/bin/interactive.rs
src/bin/io/args.rs
src/bin/io/config.rs
src/bin/io/mod.rs
src/bin/io/status.rs
src/bin/main.rs

This PR adds proper logging capabilities to the wallet.
User can now set `log_level` and `log_type` as runtime args or through configuration file.
In headless mode, anything that's not strictly program output will be redirected to `stderr`.
Resolves #11

Setup proper logging capabilities

---

CHANGELOG.md
src/bin/io/config.rs
src/bin/main.rs

- Update CHANGELOG.md
- Change `LoggingConfig` to be optional
Currently only the fields under `[logging]` section in the `config.toml`
are optional, therefore the program expects to find *at least* an
empty section.
However, the section was introduced in the version `0.11.0`, so loading
any wallet from an older version will stop the execution.
- Replace `error!` macro with `eprintln!` macro
This is needed to fix issue #73.
Currently the logger is instantiated too late, after the configuration
is parsed, so any configuration errors are not shown.
Since we're in the binary here and not in the library, it's okay to
use directly `eprintln!`.
Resolves #73

Running `v0.11.0` with pre-existing wallet data makes the exec dies silently

---

CHANGELOG.md
src/wallet.rs

Fix wrong condition involved `gas.is_enough()` check
The `if` statement involved `gas.is_enough()` was inverted: 
it was returning an error when the gas was enough, and passing when it wasn't.
Resolves #91

Fix wrong condition involved `gas.is_enough()

---

CHANGELOG.md
Cargo.toml

- Changed fn signature in `gas::new` to include the gas limit [#116]
- Change `request_gas_limit` fn signature to accept a gas limit option [#116]
- Change (un)stake, allow stake and withdraw default gas limits to sane defaults [#116]
- Change exported consensus keys extension to `.keys` [#114]
[0.13.0]: https://github.com/dusk-network/wallet-cli/compare/v0.12.0...v0.13.0

Bump to version `0.13.0`

---

CHANGELOG.md
Cargo.toml

- Add `execute` to create transaction for generic contract calls [#133]
- Add transaction history [#12]
- Add stake maturity epoch [#128]
- Add staking address display [#105]
- Add stake eligibility info [#124]
- Fix headless balance display [#123]

Release 0.14.0

---

CHANGELOG.md
Cargo.toml

- Cache implementation now uses rocksdb instead of microkelvin [#56]
- Throw an error there when specifying a network that does not exist [#143]

Release 0.15.0

---

CHANGELOG.md
Cargo.toml

- Change cached Note's key to be the nullifier instead of hash [#144]
- Update cache for all the possible addresses at the same time [#144]

Release 0.16.0

---

CHANGELOG.md
src/cache.rs
src/clients.rs
src/error.rs

Also throw DatabaseCorrupted error when cannot find CF. This is a new variant because rocksdb::Error doesn't allow you to construct its own instance even with `ErrorKind` (`ErrorKind::Corrupted` would suit well here) but we can always create our own custom ones to provide more comprehensive errors to user
Opened because #153 closed
Closes #149

Calculate psk(s) again on state init to populate cf(s) on cache db

---

CHANGELOG.md
Cargo.toml

- Add `rkyv` dependency [#151]
- Add `dusk-merkle` dependency [#151]
- Add `Error::Utf8` variant [#151]
- Add `devnet` network to default config [#151]
- Change `rust-toolchain` to `nightly-2023-05-22` [#151]
- Change `REQUIRED_RUSK_VERSION` to `0.6.0` [#151]
- Change `Error::Canon` variant to `Error::Rkyv` [#151]
- Populate cache database with psk(s) on state init [#158]
- Change `dusk-plonk` to `0.14.0` [#169]
- Fix cache resolution for alternative networks [#151]
- Fix cache error detection [#163]
- Remove `canonical` dependency [#151]

Release 0.17

---

CHANGELOG.md
Cargo.toml

- Add support for rusk HTTP request [#173]
- Add `local` network to default.config.toml [#173]
- Change `config.toml` to use `http` instead of `grpc` endpoints [#173]
- Save the wallet.dat file with the new Rusk Binary Format [#165]
- Change blake3 with sha256 for password hashing for new Rusk Binary Format, keep using blake3 for old dat file formats [#162]
- Remove `grpc` support [#173]
- Remove `gql` support [#173]
Full changes [here](https://github.com/dusk-network/wallet-cli/compare/v0.17.0...v0.18.0)

Release 0.18.0

---

CHANGELOG.md
src/bin/command.rs
src/bin/command/history.rs
src/bin/interactive.rs
src/bin/main.rs
src/cache.rs
src/clients.rs
src/clients/sync.rs
src/rusk.rs
src/wallet.rs

Everytime the database is synced, spent notes are moved to a different column family.
This way, calculating the balance doesn't require the network anymore and cache is consistent (see also #188)
Change the `fetch_existing_nullifiers` used by wallet-core to return empty notes.
Ps: deleting notes (instead of move them) results in missing transactions from the history
Resolves #195

Decouple balance from fetch_notes/fetch_nullifiers

---

CHANGELOG.md
src/bin/command.rs
src/bin/main.rs
src/wallet.rs

- Remove `cache_sync` from `connect` and `connect_with_status`
- Add `Wallet::sync` method for sync cache update
- Add `Wallet::register_sync` method for async cache update
- Address list can now be performed offline (non interactive)

Refactor connection handling

---

CHANGELOG.md
Cargo.toml

- Add interactive stake allow [#98]
- Add optional `WALLET_MAX_ADDR` compile time env [#210]
- Fix staking address display [#204]
- Fix status overlap [#179] 
[0.19.1]: https://github.com/dusk-network/wallet-cli/compare/v0.19.0...v0.19.1

Release 0.19.1

---

CHANGELOG.md
src/bin/command.rs
src/rusk.rs

- Adapt to dusk-network/rusk#1072
- Change REQUIRED_RUSK_VERSION to `0.7.0-rc`

Fix HTTP version Handshake

---

CHANGELOG.md
Cargo.toml

- Change `REQUIRED_RUSK_VERSION` to `0.7.0-rc`
- Change the Staking Address generation. [#214]
- Change `dusk-wallet-core` to `0.22.0-plonk.0.16` [#214]
[0.20.0]: https://github.com/dusk-network/wallet-cli/compare/v0.19.1...v0.20.0

Bump version to `0.20.0`

---

CHANGELOG.md
Cargo.toml
src/bin/command.rs
src/bin/interactive.rs
src/bin/main.rs
src/lib.rs
src/wallet.rs

- Bump wallet-core to `0.24.0-plonk.0.16-rc.2`
- Bump rusk-abi to `0.12-0.rc`
- Add `name` to `export` command
- Add `seed-file` to `create` command
- Change `DEFAULT_MAX_ADDRESSES` from 255 to 25

Adapt wallet-cli to new stack

---

CHANGELOG.md
src/bin/README.md
src/bin/command.rs
src/bin/interactive.rs
src/bin/io/prompt.rs
src/error.rs
src/wallet.rs

Reflect changes in https://github.com/dusk-network/rusk/pull/1257

Remove stake_allow command

---

CHANGELOG.md
Cargo.toml
src/rusk.rs

- Change `REQUIRED_RUSK_VERSION` to `0.7.0`
- Update unclear error message [#235]
- Change provisioner key password prompt message [#238]
- Remove `stake_allow` command
[0.22.0]: https://github.com/dusk-network/wallet-cli/compare/v0.21.0...v0.22.0

Release 0.22.0

---

CHANGELOG.md
src/bin/command/history.rs
src/bin/interactive.rs
src/bin/io/gql.rs
src/bin/io/status.rs
src/lib.rs

* Change rusk-wallet to wait for tx to be included
* Improve tx history performance
* Add support for `WALLET_MAX_ADDR=1`

Small improvements

---

CHANGELOG.md
Cargo.toml

- Add support for `WALLET_MAX_ADDR` lower than `6` [#244]
- Change rusk-wallet to wait for tx to be included
- Fix tx history to avoid useless calls [#243]

Release 0.22.1

---

CHANGELOG.md
src/bin/command/history.rs

Fix tx history to show tx created with "MAX" amount
