dusk-network/wallet-cli

.github/workflows/wallet_ci.yml
- Add workflow for automated tests on PR
- Fix CI workflow assigned on wrong runners
- Change CI to be picked up by core runner
See also #5
=> Add workflow for automated tests on PR

.github/workflows/wallet_build.yml, CHANGELOG.md, README.md, src/main.rs
=> Fallback to TCP/IP on windows

src/lib/mod.rs, src/lib/prompt.rs, src/lib/wallet.rs, src/main.rs
As per @herr-seppia's [comment](https://github.com/dusk-network/wallet-cli/pull/4#discussion_r842966570)
=> Use LUX for gas price in headless mode

CHANGELOG.md, src/lib/wallet.rs
=> Prevent interactive process from quitting on wallet errors

CHANGELOG.md, Cargo.lock, Cargo.toml
- Notes cache [#650]
- Settings can be loaded from a config file [#637]
- Create config file if not exists [#647]
- Notify user when defaulting configuration [#655]
- Implementation for `State`'s `fetch_block_height` [#651]
- Option to wait for transaction confirmation [#680]
- Default to TCP/IP on Windows [#6]
- Export consensus public key as binary
- Interactive mode allows for directory and wallet file overriding [#630]
- Client errors implemented, Rusk error messages displayed without metadata [#629]
- Transactions from wallets with no balance are halted immediately [#631]
- Rusk and prover connections decoupled [#659]
- Use upper-case DUSK for units of measure [#672]
- Use DUSK as unit for stake and transfer [#668]
- `data_dir` can be properly overriden [#656]
- Invalid configuration …
=> Release 0.7

CHANGELOG.md, Cargo.lock, Cargo.toml, src/lib/config.rs, src/lib/dusk.rs, src/lib/mod.rs, src/lib/prompt.rs, src/lib/wallet.rs, src/main.rs
Proposed implementation is attempt to solve what was suggested in https://github.com/dusk-network/rusk/issues/673 taking inspiration from https://github.com/dusk-network/rusk/issues/675.
This is expected to be replaced with VM2 structures in the future.
Resolves #2
=> Introduce `Dusk` type for currency management

CHANGELOG.md, src/lib/cache.rs, src/lib/clients.rs, src/lib/mod.rs, src/lib/prompt.rs
- Fix cache bug preventing all notes to be added to the cache
- Fix address validation by parsing it immediately
Resolves #35
=> Fix address validation

CHANGELOG.md, Cargo.lock, Cargo.toml
This release includes mostly structural changes.
In terms of user-facing novelties, headless mode now outputs clean results that can be easily parsed, piped and chained to other programs.
=> Release 0.9

CHANGELOG.md, src/bin/interactive.rs
• Update CHANGELOG.md
• Add prompt `confirm_recovery_phrase`  to display the recovery phrase
Resolves #70
=> No mnphrase displayed

CHANGELOG.md, Cargo.toml
- Add prompt confirm_recovery_phrase to display the recovery phrase [#70]
- Add Windows terminal compatibility [#68]
- Change `LoggingConfig` to be optional [#73]
- Replace `error!` macro with `eprintln!` macro [#73]
=> Release v0.11.1

CHANGELOG.md, src/bin/command.rs, src/bin/interactive.rs, src/wallet.rs
=> Remove `refund_addr` withdraw argument

CHANGELOG.md, Cargo.toml, src/bin/command.rs, src/bin/io/args.rs, src/wallet.rs
=> Add `stake-allow` command

src/bin/command.rs, src/bin/interactive.rs, src/bin/io/prompt.rs, src/bin/main.rs, src/cache.rs
- Remove `expect` and `unwrap`
- Propagate errors properly
Resolves #100
=> Fix unexpected panic while quitting

.github/workflows/wallet_build.yml
=> Add libssl.3 target

CHANGELOG.md, src/wallet.rs
=> rename ext. key to keys

CHANGELOG.md, src/bin/command.rs, src/bin/interactive.rs, src/bin/io/prompt.rs, src/wallet/gas.rs
=> Default gas limit per tx type

CHANGELOG.md, src/bin/main.rs
=> Fix balance display

CHANGELOG.md, src/bin/command.rs
=> Add stake eligibility info

CHANGELOG.md, src/clients.rs
=> Add staking address display

CHANGELOG.md, src/bin/command.rs, src/clients.rs, src/lib.rs
=> Add stake maturity epoch

src/bin/io/gql.rs
• Change error handeling use `thiserror` crate
• Modify `tx_status`
Resolves #102
=> Improve gql code structure

CHANGELOG.md, Cargo.toml, src/bin/README.md, src/bin/command.rs, src/bin/command/history.rs, src/bin/interactive.rs, src/bin/io/gql.rs, src/bin/main.rs, src/clients.rs, src/lib.rs, src/wallet.rs
=> Add Transaction history

.github/workflows/wallet_ci.yml, Cargo.toml
=> Add overflow-checks to release mode

CHANGELOG.md, src/bin/main.rs, src/cache.rs
- Cache error are now properly reported
- Simplify the column families creation to support multiple address length
Resolves #163
=> Fix cache error detection

Cargo.toml, src/clients.rs
This is a followup PR of https://github.com/dusk-network/rusk/pull/942
=> Upgrade to plonk 14

CHANGELOG.md, src/dat.rs, src/wallet.rs
Closes #165 
Start saving files with new header
=> Save dat files with the new format

CHANGELOG.md, Cargo.toml, default.config.toml, src/bin/command/history.rs, src/bin/config.rs, src/bin/interactive.rs, src/bin/io/gql.rs, src/bin/main.rs, src/bin/settings.rs, src/clients.rs, src/error.rs, src/lib.rs, src/rusk.rs, src/wallet.rs
- Add support for rusk HTTP request
- Add `local` network to default.config.toml
- Change `config.toml` to use `http` instead of `grpc` endpoints 
- Remove `grpc` support
- Remove `gql` support
To test it against a [local node](https://github.com/dusk-network/rusk/blob/master/README.md#use)
`cargo r --release --bin rusk-wallet -- -p <wallet_folder> -n local`
=> Add support for Rusk Event System

CHANGELOG.md, src/clients.rs
=> Fix fetch_notes buffer

CHANGELOG.md, src/bin/interactive.rs, src/bin/main.rs, src/dat.rs, src/error.rs, src/wallet.rs
=> Fix bug where we return early when there's no wallet file in interactive

src/clients.rs
=> Add sync before fetching notes

CHANGELOG.md, src/cache.rs, src/clients/sync.rs
- Change `fetch_notes` to use note's position instead of note's height
=> Improve fetch notes performance

CHANGELOG.md, Cargo.toml
This PR updates the current `main` version to reflect the crates-io releases
No new feature have been added
Releases 0.18.0 and 0.18.1 will be yanked on crates-io
=> Release 0.18.2

CHANGELOG.md, src/bin/interactive.rs, src/bin/io/prompt.rs, src/dat.rs
=> Fix regression when saving old wallet file as latest RBS

CHANGELOG.md, src/clients.rs
=> Fix staking address display

CHANGELOG.md, src/clients.rs, src/clients/sync.rs
=> Fix status overlap

CHANGELOG.md, src/bin/interactive.rs, src/bin/io/prompt.rs
Resolves https://github.com/dusk-network/wallet-cli/issues/98
=> Add interactive stake allow

CHANGELOG.md, Cargo.toml, src/bin/command.rs, src/bin/interactive.rs, src/lib.rs
Add optional `WALLET_MAX_ADDR` compile time env
Resolves #210
=> Allow to specify different MAX_ADDRESSES

CHANGELOG.md, Cargo.toml, src/bin/command.rs, src/bin/command/history.rs, src/bin/interactive.rs, src/bin/io/gql.rs, src/bin/main.rs, src/wallet.rs
See also https://github.com/dusk-network/rusk/pull/1091
Resolves https://github.com/dusk-network/wallet-cli/issues/214
=> Upgrade `dusk-wallet-core` to `0.22.0-plonk.0.16`

CHANGELOG.md, src/wallet.rs
See https://github.com/dusk-network/wallet-cli/issues/218
=> Add `spending_keys` method

CHANGELOG.md, Cargo.toml
- Add `spending_keys` to wallet impl [#218] 
[0.20.1]: https://github.com/dusk-network/wallet-cli/compare/v0.20.0...v0.20.1
=> Release 0.20.1

.github/workflows/wallet_build.yml, CHANGELOG.md, Cargo.toml
- Add `seed-file` to `create` command [#226] 
- Add `name` to `export` command 
- Fix `stake_allow` command [#222] 
- Change `dusk-wallet-core` to `0.24.0-plonk.0.16-rc.2`
- Change `DEFAULT_MAX_ADDRESSES` from 255 to 25
=> Release 0.21.0

CHANGELOG.md, src/bin/main.rs, src/error.rs
=> Update Rusk conn and password error messages

CHANGELOG.md, src/bin/command.rs
=> Update prov key password set prompt msg
